[package]
name = "fastn-lang"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
description.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true


[dependencies]
serde_json.workspace = true
serde.workspace = true
fastn-section.workspace = true
fastn-unresolved.workspace = true
async-trait.workspace = true

[dev-dependencies]
serde_json.workspace = true

