[package]
name = "fastn-jdebug"
version = "0.1.1"
authors.workspace = true
edition.workspace = true
description.workspace = true
license = "BSD-3-Clause"
repository.workspace = true
homepage.workspace = true

[dependencies]
arcstr.workspace = true
serde_json = "1"
