[package]
name = "fpm"
version = "0.1.0"
authors = ["Amit Upadhyay <upadhyay@gmail.com>", "Shobhit Sharma <shobhit@fifthtry.com>"]
edition = "2021"
description = "fpm: FTD Package Manager"
license = "MIT"
repository = "https://github.com/fifthtry/fpm"
homepage = "https://www.fifthtry.com/fpm/"


[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
ftd = { version = "0.1.8", path = "../ftd/ftd" }
clap = "2.33.3"

[dev-dependencies]
rusty-hook = "^0.11.2"
