[package]
name = "fpm"
version = "0.1.11"
authors = [
    "Amit Upadhyay <upadhyay@gmail.com>",
    "Arpita Jaiswal <arpita@fifthtry.com>",
    "Shobhit Sharma <shobhit@fifthtry.com>",
    "Abrar Khan <abrark@fifthtry.com>",
]
edition = "2018"
description = "fpm: FTD Package Manager"
license = "MIT"
repository = "https://github.com/FifthTry/fpm"
homepage = "https://fpm.dev"
# build = "build.rs"

[features]
controller = []
remote = []
local = []


[dependencies]
#ftd = { path = "../ftd" }
#reqwest = { version = "0.11.10", features = ["blocking"] }
actix-files = "0.6"
actix-web = "4"
antidote = "1"
async-recursion = "1"
camino = "1"
chrono = "0.4"
clap = "3"
colored = "2"
diffy = "0.2"
edit = "0.1"
fluent = "0.16"
ftd = { git = "https://github.com/FifthTry/ftd", rev = "9d1d206" }
futures = "0.3"
ignore = "0.4"
indoc = "1"
intl-memoizer = "0.5"
itertools = "0.10"
lazy_static = "1"
mime_guess = "2"
realm-lang = "0.1"
regex = "1"
rusqlite = { version = "0.28", features = ["bundled"] }
semver = "1"
serde = { version = "1", features = ["derive"] }
serde_derive = "1"
serde_json = "1"
sha2 = "0.10"
thiserror = "1"
url = "2"
zip = "0.6"

[dependencies.reqwest]
# We are using an older reqwest on purpose, fpm does not work with
# latest reqwest. Using latest will cut down number of dependencies
# from about 425 to 340.
version = "0.9"
features = ["default-tls-vendored"]
# latest ones
# version = "0.11"
# features = ["native-tls-vendored"]


[dependencies.tokio]
version = "1"
features = [
    "rt-multi-thread",
    "fs",
]

[dev-dependencies]
fbt-lib = "0.1.18"
indoc = "1"
pretty_assertions = "1"
#rusty-hook = "^0.11.2"
