[package]
name = "fastn-compiler"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
description.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true

[features]
owned-tdoc = ["fastn-resolved/owned-tdoc"]

[dependencies]
fastn-section.workspace = true
fastn-resolved.workspace = true
fastn-builtins.workspace = true
fastn-unresolved.workspace = true
indexmap.workspace = true
