[package]
name = "fastn-compiler"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
description.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true


[dependencies]
fastn-section.workspace = true
fastn-resolved.workspace = true
fastn-unresolved.workspace = true
string-interner.workspace = true


