[package]
name = "ftd-tc"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
description.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true

[dependencies]
ftd-ast.workspace = true
ftd-p1.workspace = true
thiserror.workspace = true
