[package]
name = "fastn-section"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
description.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true

[dependencies]
arcstr.workspace = true
serde.workspace = true
fastn-jdebug.workspace = true
serde_json.workspace = true
