[package]
name = "fastn-p1"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
description.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true


[dependencies]
serde.workspace = true
logos.workspace = true
#lalrpop-util.workspace = true

[dev-dependencies]
insta.workspace = true

[build-dependencies]
#lalrpop.workspace = true

[profile.dev.package]
insta.opt-level = 3
similar.opt-level = 3