[package]
name = "fastn-unresolved"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
description.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true

[dependencies]
arcstr.workspace = true
fastn-section.workspace = true
fastn-type.workspace = true
string-interner.workspace = true

[dev-dependencies]
fastn-jdebug.workspace = true
serde_json.workspace = true
