[REQ-server]
partof = 'REQ-purpose'
text = 'FPM acts a HTTP server. It can be used to preview the package content locally. `fpm` server can also be deployed to serve your package content if the the fpm package contains dynamic features.'
