[package]
name = "fastn-resolved"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
description.workspace = true
license = "BSD-3-Clause"
repository.workspace = true
homepage.workspace = true

[dependencies]
indexmap.workspace = true
serde.workspace = true
