[package]
name = "fastn-wasm"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
description.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true

[dependencies]
wasmtime.workspace = true
serde_json.workspace = true
serde.workspace = true