[package]
name = "fastn"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
description.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true

[dependencies]
async-trait.workspace = true
fastn-core.workspace = true
fastn-compiler.workspace = true
fastn-runtime.workspace = true
fastn-unresolved.workspace = true
serde_json.workspace = true
tokio.workspace = true
