[package]
name = "fastn-ds"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
description.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true

[dependencies]
tokio.workspace = true
thiserror.workspace = true
ftd.workspace = true
dashmap.workspace = true
actix-web.workspace = true
deadpool.workspace = true
diesel-async.workspace = true
camino.workspace = true
diesel.workspace = true

