name: Build release

on:
  push:
    branches: [ main ]
    paths:
     - '**.rs'

jobs:
  release:
    name: release ${{ matrix.target }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: actions-rs/toolchain@v1
      - name: Run Build
        id: build-linux
        continue-on-error: true
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release
      - uses: actions/upload-artifact@master
        with:
          name: SSR_BUILD
          path: target/release/fpm