name: Test nix on 

on:
  push:
    branches: [ feat/nix ]
jobs:
  release-ubuntu:
    name: Build for Linux
    runs-on: ubuntu-latest
    env:
      CARGO_TERM_COLOR: always
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@v9
      - name: build linux-musl
        run: nix build -L .#fastn
      - name: test the output binary
        run: |
          ldd result/bin/fastn
          ./result/bin/fastn --version
      # - name: Build-musl
      #   run: |
      #     echo "Building static binaries using ekidd/rust-musl-builder"
      #     docker build -t fastn-build-image -f .github/Dockerfile .
      #     docker run --name fastn-build fastn-build-image
      #     mkdir -p out
      #     docker cp fastn-build:/home/rust/src/target/x86_64-unknown-linux-musl/release/fastn out/
      # - name: run fastn
      #   run: out/fastn --version
      # - uses: actions/upload-artifact@v4
      #   with:
      #     name: linux_musl_x86_64
      #     path: out/fastn
  release-windows:
    name: Build for win 64
    runs-on: ubuntu-latest
    env:
      CARGO_TERM_COLOR: always
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@v9
      - name: build mingwW64
        run: nix build -L .#fastn-win
      - name: test the output binary
        # wine?
        # run: ldd result/bin/fastn.exe
        # run: ./result/bin/fastn.exe --version
        run: |
          ls result/bin/
          file result/bin/fastn.exe
          ldd result/bin/fastn.exe
  release-macos:
    name: Build for MacOS
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@v9
      - name: build mac
        run: nix build -L .#fastn
      - name: test the output binary on mac
        run: |
          ldd result/bin/fastn
          ./result/bin/fastn --version
      # - name: run fastn
      #   run: ./target/release/fastn --version
      # - uses: actions/upload-artifact@v4
      #   with:
      #     name: macos_x64_latest
      #     path: |
      #       target/release/fastn
